resources:
  - name: mydotnetRepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: nethrasruthinethra/square # replace jfrog with your username or org name
      branches:
        include: main
        
  - name: mydotnetInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: hello
      buildName: SampleApp
      buildNumber: 1   
      
pipelines: 
  - name: my_dotnetpipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello" 
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: mydotnetRepo
          outputResources:
            - name: mydotnetInfo            
        execution:
          onExecute:
            - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            - sudo yum update -y && yum install -y dotnet-sdk-2.0.0
            - dotnet restore SquareApp.sln
            - dotnet build SquareApp.sln
           
    
