resources:
  - name: mydotnetRepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: nethrasruthinethra/square # replace jfrog with your username or org name
      branches:
        include: main
        
  - name: mydotnetInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: hello
      buildName: SampleApp
      buildNumber: 1   
      
pipelines: 
  - name: my_dotnetpipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello" 
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: mydotnetRepo
          outputResources:
            - name: mydotnetInfo            
        execution:
          onExecute:
            - wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            - sudo yum install dpkg-devel dpkg-dev -y
            - dpkg -i packages-microsoft-prod.deb
            - dotnet restore SquareApp.sln
            - dotnet build SquareApp.sln
           
    
